app/app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [    
    path('admin/', admin.site.urls), 
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')), 
    path('', include('pages.urls') ), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

app/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

app/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('menu/', views.menu, name="menu"),
    path('blog/', views.blog, name="blog"),
    path('contact/', views.contact, name="contact"),
    path('elements/', views.elements, name="elements"),  
]

app/cart/models.py
from django.db import models

# Create your models here.

app/orders/models.py
from django.db import models
from pages.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=13, default= '')   
    address = models.CharField(max_length=250) 
    created = models.DateTimeField(verbose_name='Время создания заказа',auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Время изменения  заказа',auto_now=True)
    paid = models.BooleanField(verbose_name= 'Оплачено' ,default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):        
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

app/pages/models.py
from django.db import models
from datetime import datetime



class Category(models.Model):
    name = models.CharField(verbose_name='Тип блюда', max_length=100, db_index= True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        
    def __str__(self):
        return self.name



class Product(models.Model):
    category = models.ForeignKey(Category,verbose_name='Категория', related_name='products', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Название блюда', max_length=150, db_index= True)
    slug = models.CharField(max_length=150, db_index= True, unique=True)
    image = models.ImageField(upload_to='product/%Y/%m/%d/')
    description = models.TextField(verbose_name='Описание блюда', max_length=1000)
    price = models.DecimalField(verbose_name='Цена блюда',max_digits=10, decimal_places=2)
    available = models.BooleanField(verbose_name='Наличие блюда', default= True)
    new  = models.BooleanField(verbose_name="Новое блюдо", default= False)


    class Meta:
        ordering = ('name',)
        verbose_name = 'Блюдо'
        verbose_name_plural = 'Блюда'
        index_together = (('id', 'slug'), )
        
    def __str__(self):
        return self.name    

        

app/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

app/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'address',]

app/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from pages.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

app/orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # очистка корзины
            cart.clear()
            return render(request, 'orders/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm
        return render(request, 'orders/create.html',{'cart': cart, 'form': form})

app/pages/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def index(request):
    products = Product.objects.filter(available= True)
    pizza_category = get_object_or_404(Category, slug= 'pizza')
    pizza_products = products.filter(category = pizza_category)
    sushi_category = get_object_or_404(Category, slug= 'sushi')
    sushi_products = products.filter(category = sushi_category)  
    dessert_category = get_object_or_404(Category, slug= 'dessert')
    dessert_products = products.filter(category = dessert_category)  
    new_products = products.filter(new = True)    
    context ={
        'pizza': pizza_products,
        'sushi': sushi_products,      
        'dessert': dessert_products, 
        'new': new_products,           
    }    
    return render(request, 'pages/index.html',context)


def about(request):
    return render(request, 'pages/about.html')


def menu(request):
    products = Product.objects.filter(available= True)
    pizza_category = get_object_or_404(Category, slug= 'pizza')
    pizza_products = products.filter(category = pizza_category)
    sushi_category = get_object_or_404(Category, slug= 'sushi')
    sushi_products = products.filter(category = sushi_category)  
    dessert_category = get_object_or_404(Category, slug= 'dessert')
    dessert_products = products.filter(category = dessert_category) 
    cart_product_form = CartAddProductForm()
    context ={
        'pizza': pizza_products,
        'sushi': sushi_products,      
        'dessert': dessert_products,
        'cart_product_form': cart_product_form,       
    } 
    return render(request, 'pages/menu.html', context)


def blog(request):
    return render(request, 'pages/blog.html')


def contact(request):
    return render(request, 'pages/contact.html')


def elements(request):
    return render(request, 'pages/elements.html')

app/templates/base.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}page{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'styles/bootstrap-4.1.2/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}">
   
    <link rel="stylesheet" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">

    <link rel="stylesheet" href="{% static 'plugins/colorbox/colorbox.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/jquery-datepicker/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/jquery-timepicker/jquery.timepicker.css' %}">

    {% block style %}
    {% endblock  %}  

</head>

<body>
    <div class="super_container">
        {% include 'partials/_header.html' %}
        {% block content %}
        {% endblock %}
        {% include 'partials/_footer.html' %}
    </div>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'styles/bootstrap-4.1.2/popper.js' %}"></script>
    <script src="{% static 'styles/bootstrap-4.1.2/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/greensock/TweenMax.min.js' %}"></script>
    <script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
    <script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
    <script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
    <script src="{% static 'plugins/greensock/ScrollToPlugin.min.js' %}"></script>
    <script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
    <script src="{% static 'plugins/easing/easing.js' %}"></script>
    <script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
    <script src="{% static 'plugins/colorbox/jquery.colorbox-min.js' %}"></script>
    <script src="{% static 'plugins/jquery-datepicker/jquery-ui.js' %}"></script>
    <script src="{% static 'plugins/jquery-timepicker/jquery.timepicker.js' %}"></script>
    {% block script %}
    {% endblock %}
</body>

</html>

app/templates/cart/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your shoping cart</title>
    <link rel="stylesheet" href="{% static 'styles/bootstrap-4.1.2/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles/main_styles_cart.css' %}">
    <link rel="stylesheet" href="{% static 'styles/responsive_cart.css' %}">
    <link rel="stylesheet" href="{% static 'styles/responsive.css' %}">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="home_content text-center">
                    
                    <div class="home_title">
                        <h1>Your shopping cart</h1>
                        <div class="ml-auto mr-auto">
                            <table class="cart">
                                <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Product</th>
                                        <th>Quantity</th>
                                        <th>Remove</th>
                                        <th>Unit price</th>
                                        <th>Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in cart %}
                                    {% with product=item.product %}
                                    <tr>
                                        <td>
                                            <a href="{{ product.get_absolute_url }}">
                                                <img src="
                                                            {% if product.image %}
                                                                {{ product.image.url }}
                                                            {% else %}
                                                                {% static 'img/no_image.png' %}
                                                            {% endif %}">
                                            </a>
                                        </td>
                                        <td>{{ product.name }}</td>
                                        <td>{{ item.quantity }}</td>
                                        <td><a href="{% url 'cart:cart_remove' product.id%}">Remove</a></td>
                                        <td>${{ item.price }}</td>
                                        <td>${{ item.total_price }}</td>
                                    </tr>
                                    {% endwith %}
                                    {% endfor %}
                                    <tr class="total">
                                        <td>Total</td>
                                        <td colspan="4"></td>
                                        <td >{{ cart.get_total_price }}$</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <p class="text">
                            <a href="{% url 'orders:order_create' %}" class="button">
                                Checkout
                            </a>
                            <a href="{% url 'pages:menu' %}" class="button light">Continue shopping</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

app/templates/orders/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your shoping cart</title>
    <link rel="stylesheet" href="{% static 'styles/bootstrap-4.1.2/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles/main_styles_cart.css' %}">
    <link rel="stylesheet" href="{% static 'styles/responsive_cart.css' %}">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Checkout</h1>
                <div class="order-info">
                    <h3>Your order</h3>
                    <ul>
                        {% for item in cart %}
                        <li>
                            {{ item.quantity }}x {{ item.product.name }}
                            <span>${{ item.total_price }}</span>
                        </li>
                        {% endfor %}
                    </ul>
                    <p>Total: ${{ cart.get_total_price }}</p>
                </div>
                <form action="." method="post" class="order-form">
                    {{ form.as_p }}
                    <p><input type="submit" value="Place order"></p>
                    {% csrf_token %}
                </form>                
            </div>         
        </div>
        <div class="row">
            <div class="col  d-flex justify-content-center">
                <a href="{% url 'pages:menu' %}" class="button light mr-2">Continue shopping</a>
                <a href="{% url 'cart:cart_detail' %}" class="button light">
                    Return to cart</a>
            </div>            
        </div>
    </div>


</body>

</html>

app/templates/orders/created.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thank you</title>
    <link rel="stylesheet" href="{% static 'styles/bootstrap-4.1.2/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles/main_styles_cart.css' %}">
    <link rel="stylesheet" href="{% static 'styles/responsive_cart.css' %}">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Thank you</h1>
                <p class="thank">Your order has been successfully completed. Your order number is
                <strong>{{ order.id }}</strong>.</p>           
            </div>         
        </div>
        <div class="row">
            <div class="col">
                <a href="{% url 'pages:index' %}" class="button light">Home Page</a>
            </div>
        </div>
    </div>


</body>

</html>

app/templates/pages/contact.html
{% extends 'base.html/' %}
{% load static %}

{% block title %}Contact{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'styles/contact.css' %}">
<link rel="stylesheet" href="{% static 'styles/contact_responsive.css' %}">
<link rel="stylesheet" href="{% static 'styles/main_styles.css' %}">
<link rel="stylesheet" href="{% static 'styles/responsive.css' %}">
{% endblock %}

{% block content %}
	<!-- Home -->
	<div class="home">
		<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{{ STATIC_PREFIX }}images/contact.jpg" data-speed="0.8"></div>
		<div class="home_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="home_content text-center">
							<div class="home_subtitle page_subtitle">Yakuza</div>
							<div class="home_title"><h1>Contact</h1></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Contact -->

	<div class="contact">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="contact_title">Contact info</div>
					<div class="contact_text">
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus. Ut non justo eleifend, facilisis nibh ut, interdum odio. Suspendisse potenti.</p>
					</div>
					<div class="contact_logo_container">
						<div class="contact_logo_title">The Venue</div>
						<div class="contact_logo_subtitle">restaurant</div>
					</div>
				</div>
				<div class="col-xl-5 col-lg-6">
					<div class="contact_list_container d-flex flex-column align-items-lg-center justify-content-start">
						<div class="contact_list_content">
							<ul class="contact_list">
								<li class="d-flex flex-row align-items-start justify-content-start">
									<div><div>Address</div></div>
									<div>1481 Creekside Lane Avila Beach, CA 931</div>
								</li>
								<li class="d-flex flex-row align-items-start justify-content-start">
									<div><div>Phone</div></div>
									<div>+53 345 7953 324</div>
								</li>
								<li class="d-flex flex-row align-items-start justify-content-start">
									<div><div>E-mail</div></div>
									<div>yourmail@gmail.com</div>
								</li>
							</ul>
							<div class="contact_social">
								<ul class="d-flex flex-row align-items-center justify-content-start">
									<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
									<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
									<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
									<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>			
		</div>
	</div>

	<!-- Reservations -->

	<div class="reservations text-center">
		<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{{ STATIC_PREFIX }}images/reservations.jpg" data-speed="0.8"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="reservations_content d-flex flex-column align-items-center justify-content-center">
						<div class="res_stars page_subtitle">5 Stars</div>
						<div class="res_title">Make a Reservation</div>
						<div class="res_form_container">
							<form action="#" id="res_form" class="res_form">
								<div class="d-flex flex-sm-row flex-column align-items-center justify-content-start">
									<input type="text" id="datepicker" class="res_input" required="required">
									<input type="text" class="res_input timepicker" required="required">
									<select class="res_select">
										<option disabled="" selected="">2 person</option>
										<option>3 person</option>
										<option>4 person</option>
										<option>5 person</option>
										<option>6 person</option>
									</select>
								</div>
								<button class="res_button">Make a Reservation</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>		
	</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/contact.js' %}"></script>
{% endblock %}

app/templates/pages/menu.html
{% extends 'base.html/' %}
{% load static %}

{% block title %}Menu{% endblock  %}

{% block style %}
<link rel="stylesheet" href="{% static 'styles/menu.css' %}">
<link rel="stylesheet" href="{% static 'styles/menu_responsive.css' %}">
<link rel="stylesheet" href="{% static 'styles/main_styles.css' %}">
<link rel="stylesheet" href="{% static 'styles/responsive.css' %}">
{% endblock %}

{% block content %}
<!-- Home -->
<div class="home">
	<div class="parallax_background parallax-window" data-parallax="scroll"
		data-image-src="{{ STATIC_PREFIX }}images/menu.jpg" data-speed="0.8"></div>
	<div class="home_container">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="home_content text-center">
						<div class="home_subtitle page_subtitle">Yakuza</div>
						<div class="home_title">
							<h1>The Menu</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- The Menu -->

<div class="themenu">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="section_title_container text-center">
					<div class="section_subtitle page_subtitle">Something new</div>
					<div class="section_title">
						<h1>Discover Our Menu</h1>
					</div>
				</div>
			</div>
		</div>
		<div class="row themenu_text_row">
			<div class="col-lg-6">
				<div class="themenu_text">
					<p>In the Yakuza Sushi menu you will find gourmet Japanese cuisine, namely sushi and rolls. The high
						content of fish, exotic fruits gives the dishes taste and elegance.</p>
				</div>
			</div>
			<div class="col-lg-6">
				<div class="themenu_text">
					<p>
						やくざ寿司メニューには、寿司やロールパンなどのグルメな日本料理があります。魚、エキゾチックなフルーツの高い含有量は、料理に味と優雅さを与えます。</p>
				</div>
			</div>
		</div>
		<div class="row themenu_row">

			<!-- Starters -->
			<div class="col-lg-4 themenu_column">
				<div class="themenu_image"><img src="{{ STATIC_PREFIX }}images/piz.png" alt=""></div>
				<div class="themenu_col trans_400">
					<div class="themenu_col_title">Pizza</div>
					<div class="dish_list">

						<!-- Dish -->
						{% for item in pizza %}
						<div class="dish">
							<div
								class="dish_title_container d-flex flex-xl-row flex-column align-items-start justify-content-start">
								<div class="dish_title">
									<h3>{{item.name}}</h3>
								</div>
								<div class="dish_price">{{item.price}}$</div>
							</div>
							<div class="dish_contents">
								<ul class="d-flex flex-row align-items-start justify-content-start flex-wrap">
									<li>{{item.description}}</li>
								</ul>
							</div>
							<div class="dish_order">
								<form action="{% url 'cart:cart_add' item.id %}" method="post">
									{{ cart_product_form }}
									{% csrf_token %}
									<input type="submit" value="Add to cart"  class="cart_input"> 
								</form>
							</div>
						</div>
						{% endfor %}


					</div>
				</div>
			</div>

			<!-- Main -->
			<div class="col-lg-4 themenu_column">
				<div class="themenu_image"><img src="{{ STATIC_PREFIX }}images/roll.png" alt=""></div>
				<div class="themenu_col trans_400">
					<div class="themenu_col_title">Sushi</div>
					<div class="dish_list">

						<!-- Dish -->
						{% for item in sushi %}
						<div class="dish">
							<div
								class="dish_title_container d-flex flex-xl-row flex-column align-items-start justify-content-start">
								<div class="dish_title">
									<h3>{{item.name}}</h3>
								</div>
								<div class="dish_price">{{item.price}}$</div>
							</div>
							<div class="dish_contents">
								<ul class="d-flex flex-row align-items-start justify-content-start flex-wrap">
									<li>{{item.description}}</li>
								</ul>
							</div>
							<div class="dish_order">
								<form action="{% url 'cart:cart_add' item.id %}" method="post">
									{{ cart_product_form }}
									{% csrf_token %}
									<input type="submit" value="Add to cart"  class="cart_input">
								</form>
							</div>
						</div>
						{% endfor %}

					</div>
				</div>
			</div>

			<!-- Deserts -->
			<div class="col-lg-4 themenu_column">
				<div class="themenu_image"><img src="{{ STATIC_PREFIX }}images/des.png" alt=""></div>
				<div class="themenu_col trans_400">
					<div class="themenu_col_title">Desserts</div>
					<div class="dish_list">

						<!-- Dish -->
						{% for item in dessert %}
						<div class="dish">
							<div
								class="dish_title_container d-flex flex-xl-row flex-column align-items-start justify-content-start">
								<div class="dish_title">
									<h3>{{item.name}}</h3>
								</div>
								<div class="dish_price">{{item.price}}$</div>
							</div>
							<div class="dish_contents">
								<ul class="d-flex flex-row align-items-start justify-content-start flex-wrap">
									<li>{{item.description}}</li>
								</ul>
							</div>
							<div class="dish_order">
								<form action="{% url 'cart:cart_add' item.id %}" method="post">
									{{ cart_product_form }}
									{% csrf_token %}
									<input type="submit" value="Add to cart" class="cart_input">
								</form>
							</div>
						</div>
						{% endfor %}

					</div>
				</div>
			</div>
		</div>
	</div>
</div>



<!-- Reservations -->

<div class="reservations text-center">
	<div class="parallax_background parallax-window" data-parallax="scroll"
		data-image-src="{{ STATIC_PREFIX }}images/reservations.jpg" data-speed="0.8"></div>
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="reservations_content d-flex flex-column align-items-center justify-content-center">
					<div class="res_stars page_subtitle">5 Stars</div>
					<div class="res_title">Make a Reservation</div>
					<div class="res_form_container">
						<form action="#" id="res_form" class="res_form">
							<div class="d-flex flex-sm-row flex-column align-items-center justify-content-start">
								<input type="text" id="datepicker" class="res_input" required="required">
								<input type="text" class="res_input timepicker" required="required">
								<select class="res_select">
									<option disabled="" selected="">2 person</option>
									<option>3 person</option>
									<option>4 person</option>
									<option>5 person</option>
									<option>6 person</option>
								</select>
							</div>
							<button class="res_button">Make a Reservation</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/menu.js' %}"></script>
{% endblock %}

app/templates/partials/_footer.html
{% load static %}
<!-- Footer -->

<footer class="footer">
    <div class="container">
        <div class="row">

            <!-- Footer Logo -->
            <div class="col-lg-3 footer_col">
                <div class="footer_logo">
                    <div class="footer_logo_title">Yakuza</div>
                    <div class="footer_logo_subtitle">restaurant</div>
                </div>
                <div class="copyright">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <p style="line-height: 1.2;">Copyright &copy;<script>
                            document.write(new Date().getFullYear());
                        </script> 
                        Copyright © 2020 All rights reserved This site was created with <i class="fa fa-heart-o"
                            aria-hidden="true"></i> by Alexandr Dovhal` and Denis Leshchuk.
                    </p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>

            <!-- Footer About -->
            <div class="col-lg-6 footer_col">
                <div class="footer_about">
                    <p>Due to the coronavirus pandemic, we started working to order at home. You can either book a table and visit our restaurant, or order with home delivery. We work for you. Your "Yakuza".</p>
                </div>
            </div>

            <!-- Footer Contact -->
            <div class="col-lg-3 footer_col">
                <div class="footer_contact">
                    <ul>
                        <li class="d-flex flex-row align-items-start justify-content-start">
                            <div>
                                <div class="footer_contact_title">Address:</div>
                            </div>
                            <div class="footer_contact_text">481 Creekside Lane Avila CA 93424</div>
                        </li>
                        <li class="d-flex flex-row align-items-start justify-content-start">
                            <div>
                                <div class="footer_contact_title">Phone:</div>
                            </div>
                            <div class="footer_contact_text">+53 345 7953 32453</div>
                        </li>
                        <li class="d-flex flex-row align-items-start justify-content-start">
                            <div>
                                <div class="footer_contact_title">Email:</div>
                            </div>
                            <div class="footer_contact_text">YakuzaRest@gmail.com</div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- End Footer -->